# Ahmed Abdelrazik
ThreAFFAAFASFSFAFSAFAFAFAFAFAFAFASFASFASFAFASFASFAFASFSAFFASFFSAFAFsFAFAFASFSFAFASF = [0]
for q in range(1,1667):
    e = str(q)
    if q%3 !=0 and e[-1] != "3":
        ThreAFFAAFASFSFAFSAFAFAFAFAFAFAFASFASFASFAFASFASFAFASFSAFFASFFSAFAFsFAFAFASFSFAFASF.append(q)
 
for _ in range(int(input())):
    print(ThreAFFAAFASFSFAFSAFAFAFAFAFAFAFASFASFASFAFASFASFAFASFSAFFASFFSAFAFsFAFAFASFSFAFASF[int(input())])